services:
  # go-rinha-de-backend:
  #   build:
  #     context: .
  #     dockerfile: GoRinha.dockerfile
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - payment-processor

  # doctor:
  #   build:
  #     context: .
  #     dockerfile: Doctor.dockerfile
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   networks:
  #     - payment-processor

networks:
  rinha-backend:
    name: rinha-backend
    driver: bridge
  payment-processor:
    external: true
