services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  api1: &api
    container_name: api-1
    hostname: api1
    build:
      context: ./docker/go
      dockerfile: GoProxy.dockerfile
    restart: always
    environment:
      - APP_PORT=8080
      - INSTANCE_ID=1
      - RABBITMQ_URL=amqp://rinha:rinha@rabbitmq:5672/
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "30MB"
    networks:
      - rinha-backend
    depends_on:
      broker:
        condition: service_healthy

  api2:
    <<: *api
    container_name: api-2
    hostname: api2
    environment:
      - APP_PORT=8080
      - INSTANCE_ID=2
      - RABBITMQ_URL=amqp://rinha:rinha@rabbitmq:5672/

  broker:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    networks:
      - rinha-backend
    environment:
      RABBITMQ_DEFAULT_USER: rinha
      RABBITMQ_DEFAULT_PASS: rinha
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3

  keydb:
    image: eqalpha/keydb:alpine
    container_name: keydb
    ports:
      - "6379:6379"
    networks:
      - rinha-backend
    restart: always

  worker1: &worker
    container_name: worker-1
    hostname: worker1
    build:
      context: ./docker/go
      dockerfile: GoWorker.dockerfile
    restart: always
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - KEYDB_SERVICE_URL=keydb:6379
      - INSTANCE_ID=worker-1
      - RABBITMQ_URL=amqp://rinha:rinha@rabbitmq:5672/
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "30MB"
    networks:
      - rinha-backend
      - payment-processor
    depends_on:
      broker:
        condition: service_healthy

  worker2:
    <<: *worker
    container_name: worker-2
    hostname: worker2
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - KEYDB_SERVICE_URL=keydb:6379
      - INSTANCE_ID=worker-2
      - RABBITMQ_URL=amqp://rinha:rinha@rabbitmq:5672/
    depends_on:
      broker:
        condition: service_healthy

  worker3:
    <<: *worker
    container_name: worker-3
    hostname: worker3
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - KEYDB_SERVICE_URL=keydb:6379
      - INSTANCE_ID=worker-3
      - RABBITMQ_URL=amqp://rinha:rinha@rabbitmq:5672/
    depends_on:
      broker:
        condition: service_healthy
  # doctor:
  #   build:
  #     context: .
  #     dockerfile: Doctor.dockerfile
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   networks:
  #     - payment-processor

networks:
  rinha-backend:
    name: rinha-backend
    driver: bridge
  payment-processor:
    external: true
