services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  api1: &api
    hostname: api1
    build:
      context: ./docker/go
      dockerfile: GoProxy.dockerfile
    restart: always
    environment:
      - APP_PORT=8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - RABBITMQ_URL=amqp://rinha:rinha@rabbitmq:5672/
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "30MB"
    networks:
      - rinha-backend
    depends_on:
      broker:
        condition: service_healthy

  api2:
    <<: *api
    hostname: api2
    environment:
      - APP_PORT=8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - RABBITMQ_URL=amqp://rinha:rinha@rabbitmq:5672/

  broker:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    networks:
      - rinha-backend
    environment:
      RABBITMQ_DEFAULT_USER: rinha
      RABBITMQ_DEFAULT_PASS: rinha
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 2s
      retries: 3

  # doctor:
  #   build:
  #     context: .
  #     dockerfile: Doctor.dockerfile
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   networks:
  #     - payment-processor

networks:
  rinha-backend:
    name: rinha-backend
    driver: bridge
  payment-processor:
    external: true
